### ISSUE TITLE
Fade in Header component *before* fully scrolled through Large Header

### ISSUE THREAD

**Issue by bencreynolds** [codeherence/react-native-header#14]
Taking a look at your Twitter example, it suffers the same issue I’m facing. I have a relatively large “LargeHeader” component. Scrolling through the header causes the main title to go off screen long before I reach the bottom of the component (which triggers the transition to show the “Header” component.

Hopefully that made sense. I can explain further if needed.

Maybe I’m missing something, but is there a way to trigger the “transition” much earlier in the scroll position?

Thanks.

**Comment by e-younan** [comment]
There isn't a way at the moment, however I was already thinking about adding something like this. If I understand you correctly, you want the transition between the `LargeHeader` and `Header` component to begin at some arbitrary `y` value, rather than the end of the `LargeHeader` correct?

**Comment by e-younan** [comment]
It doesn't actually. It ends up being a child component of the ScrollView, or swapped in as the HeaderComponent of the virtualized lists. Check out the source code, it's pretty straightforward.

If you have a screenshot or video, it'll help me figure out what space you're specifically referring to.

**Comment by e-younan** [comment]
This is intended by the implementation. At the moment, the HeaderComponent will sit above the scroll container, and the LargeHeaderComponent will end up as a child of it.

When I originally designed this, I made it so that the Header will stay fixed at the top, and have a general height that is similar to native primitives, and the LargeHeader would be a component that has a dynamic height.

So in your case, it's somewhat intended that the Header stay smaller, and you add the extra space as part of the LargeHeader instead.

**Comment by e-younan** [comment]
I'm working on this right now and will have a PR up in a few minutes. Sorry for the delay, have been quite busy with an application I was building.

**Comment by e-younan** [comment]
https://github.com/codeherence/react-native-header/pull/17

**Comment by e-younan** [comment]
This is released in [0.10.0](https://github.com/codeherence/react-native-header/releases/tag/v0.10.0), let me know if it works.
