### ISSUE TITLE
feat: Ability to specify ScrollView component

### ISSUE THREAD

**Issue by vyobukhov** [codeherence/react-native-header#36]
## Feature Request

It would be nice to have an option to specify which component to use as a scroll component

## Use Case

I have screens with forms inside ScrollView and there is no easy way to replace default ScrollView with an KeyboardAwareScrollView from react-native-keyboard-controller

## Additional Information

https://github.com/kirillzyusko/react-native-keyboard-controller

**Comment by e-younan** [comment]
If you want to interop with that library, you need to use the hooks they provide to avoid the keyboard, instead of the component.

You can use the method explained here: https://kirillzyusko.github.io/react-native-keyboard-controller/docs/guides/interactive-keyboard

If you absolutely need to use that component, you can do something similar to this: https://kirillzyusko.github.io/react-native-keyboard-controller/docs/api/components/keyboard-aware-scroll-view#flatlistflashlistsectionlist-etc
