### ISSUE TITLE
feat: facebook header behaviour- hide header on scroll down, appear on scroll up

### ISSUE THREAD

**Issue by Bogdastotel** [codeherence/react-native-header#37]
## Feature Request

Achieve hide header on scroll down and re-appear on scrolling up - Facebook behaviour

## Use Case

Facebook header behaviour

## Proposed Solution

Can the default behaviour be reverted?
## Additional Information

Just look at the fb app

**Comment by Bogdastotel** [comment]
EDIT: one way to make this work is to handle onScrollWorklet to track the scroll direction and change the shared value opacity that we can pass to the Header component as showNavBar value (0 or 1)

**Comment by e-younan** [comment]
Hey there, I won't be able to work on this right now, but isn't this already possible with your approach if you use the [absoluteHeader](https://react-native-header.codeherence.com/docs/components/scroll-view-with-headers#absoluteheader) prop too?

This is a little more involved than just doing that, because some features of the ScrollView break (e.g., sticky header indices) when this approach is used. Right now, you can do something like the following:

```tsx

interface HeaderComponentProps extends ScrollHeaderProps {
  headerTranslationY: SharedValue<number>;
}

const HeaderComponent: React.FC<...> = ({ headerTranslationY }) => {

  const animatedHeaderStyle = useAnimatedStyle(() => {
    // Just translate the header upwards or downwards using the `transform` properly using `headerTranslationY `
  });  

  return (
    <Animated.View style={animatedHeaderStyle}>
       <Header ... />
   </Animated.View>
  )
}
```

and the component is used like so:

```tsx
const Page = () => {
  const headerTranslationY = useSharedValue(0);

  return (
    <ScrollViewWithHeaders 
      HeaderComponent={hcp => <HeaderComponent {...hcp} headerTranslationY={headerTranslationY} />}
      absoluteHeader
      onScrollWorklet={(event) => {
        "worklet";
        // Adjust the headerTranslationY based on the scroll's event value (use the translation values).
      }}
    />
  )
}
```

This was all written in the PR editor so the code might not be accurate, but it is generally what you should do to achieve that.

**Comment by e-younan** [comment]
I'll add an example of this in the example repo when I free up.
